name: Fuzz

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
          profile: minimal
          toolchain: nightly
          override: true
    - name: Install cargo fuzz
      run: cargo install cargo-fuzz
    - name: Build
      run: cargo build --verbose
    - name: Cache fuzzy corpus
      uses: actions/cache@v3
      with:
        path: fuzz/corpus
        key: fuzz-corpus
    - name: fuzzy common
      run: cargo fuzz run common -- -max_total_time=60
    - name: fuzzy notes
      run: cargo fuzz run notes -- -max_total_time=60
    - name: fuzzy symver
      run: cargo fuzz run symver -- -max_total_time=60
    - name: fuzzy symbol_table
      run: cargo fuzz run symbol_table -- -max_total_time=60
    - name: fuzzy stream
      run: cargo fuzz run stream -- -max_total_time=60
